spring.application.name=BootMsProj01-EurekaServer

#Eureka server
server.port=8761

#override default property values the this project as Eureka server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false 