spring.application.name=BootProj05-ValueAnnotaion-SPEL

#DS catalig
ds1.xrayRate=3000
ds.mriRate=5000
ds.ctscanRate=6000
ds.bpRate=300
ds.diabeticTestRate=6000
ds.twoDRate=5000

#Diagnostic Center Infermation
dc.name=Applo
dc.addrs=hyd