spring.application.name=BootRestProj09-MiniProject-ActorAPI

#Data source Configuration
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=USER1
spring.datasource.password=USER1

#Hibernate-JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Embeded server port
server.port=4041
#Configure Context path
server.servlet.context-path=/ActorAPIApp