 spring.application.name=BootProj11-MiniProject-Profiles
 
#if active profile does not match with the any child profile
# then application.properties file properties will get the chance .

#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
#spring.datasource.username=USER1
#spring.datasource.password=USER1

 #Acativate profiles
 spring.profiles.active=pre-prod

 #include the profile
 #we include the child profile to application profile 
 spring.profiles.include=prod