spring.application.name=BootMVCProj06-FormDataBinding-HtmlTags



#View Resolver Configuration
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

#Embedded Server port
server.port=4041

server.servlet.context-path=/FormDataBinding