spring.application.name=BootProj06-BulkInjectionUsing-ConfigurationProperties

#pertional information
#simple properties
per.info.name=rajesh
per.info.addrs=hyd
per.info.mobileno=999999
per.info.age=60
per.info.salary=5000

#for Array value Annotaion
#per.info.nick-names[0]=raju
#per.info.nick-names[1]=bujji
#per.info.nick-names[2]=deepak

#inline style of injection
per.info.nick-names=chhina,raji,bujji

#for List
per.info.friends[0]=sreenibas
per.info.friends[1]=ramesh
per.info.friends[2]=chinu

#for Set
per.info.phones[0]=9999999
per.info.phones[1]=555555
per.info.phones[2]=7777777

#for Map
per.info.idDetails.aadhar=948784
per.info.idDetails.pan=8888888
per.info.idDetails.voter=5463784

#HAS-A properties
per.info.comp.name=raja
per.info.comp.location=hyd
per.info.comp.size=300


#my.info.name=ritik
#configure properties file
#spring.config.import=com/nt/commons/info.properties