# Base file(english label)
home.title=Actor Operation
home.link=Report

actor.name=Actor name 
actor.addrs=Actor Addres
actor.fee=Actor Fee
actor.catagory=Actor Catagory
actor.id=Actor Id

registration.title=Actor Registration Page
registration.registerbtn=register
registration.canclebtn=cancle

report.title=Actors Report page
retort.operation=Operation
report.reportnotfound=No Report Found
report.pageno=Page no
report.register=Register Actor
report.report=Report
report.first=first
report.next=next
report.previous=previous
report.last=last

edit.title=Actor Details Edit Page
edit.editbtn=edit actor
edit.canclebtn=cancle