spring.application.name=BootMVCProj13-MiniProject-ServerManagedjdbcConpool

#Active server managed jdbc con pool
spring.datasource.jndi-name=java:/comp/env/DsJndi


#JPA-Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#View Resulverconfiguration
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp


#Embedded server port no
server.port=4041

#context path
#server.servlet.context-path=project