# Base file(english label)
home.title=Actor Operation
home.link=Report

actor.name=Actor name 
actor.addrs=Actor Addres
actor.fee=Actor Fee
actor.catagory=Actor Catagory

actor.registration.title=Actor Registration Page
actor.registration.registerbtn=register
actor.registration.canclebtn=cancle

actor.report.title=Actors Report page
actor.retort.operation=Operation
actor.report.reportnotfound=No Report Found
actor.report.pageno=Page no
actor.report.register=Register
actor.report.report=Report
actor.report.first=first
actor.report.next=next
actor.report.previous=previous
actor.report.last=last

actor.edit.title=Actor Details Edit Page
actor.edit.editbtn=edit actor
actor.edit.canclebtn=cancle